/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package net.imthinker.ti.textnormalizer;

import java.text.Normalizer;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

@Kroll.module(name="TiTextNormalizer", id="net.imthinker.ti.textnormalizer")
public class TiTextNormalizerModule extends KrollModule {
    @Kroll.constant
    final public static int NFC = 200;
    @Kroll.constant
    final public static int NFD = 201;
    @Kroll.constant
    final public static int NFKC = 202;
    @Kroll.constant
    final public static int NFKD = 203;

    public TiTextNormalizerModule() {
        super();
    }

    private Normalizer.Form getForm(final int form) {
        switch(form) {
            case NFC:
                return Normalizer.Form.NFC;
            case NFD:
                return Normalizer.Form.NFD;
            case NFKC:
                return Normalizer.Form.NFKC;
            case NFKD:
                return Normalizer.Form.NFKD;
            default:
                return Normalizer.Form.NFC;
        }
    }

    @Kroll.method
    public String normalize(final String text, final int form) {
        return Normalizer.normalize(text, getForm(form));
    }

    @Kroll.method
    public boolean isNormalized(final String text, final int form) {
        return Normalizer.isNormalized(text, getForm(form));
    }
}
